### ISSUE TITLE
Some missing modules

### ISSUE THREAD

**Issue by okada-masashi** [hyanan16/SVDD-molecule#1]
Thank you for releasing the excellent source code.

The modules `evaluation` and `moses` are referenced but do not appear in the current repository.
Could you please add these modules?

**Comment by hyanan16** [comment]
Hi,

Thanks for your interest in our work. We have updated the module `evaluation` and the environment setup in README, which contains the installation of `Moses` package. Some of the environment package versions might need adjustments based on server configurations. Please let us know if there are other issues.

**Comment by okada-masashi** [comment]
Thanks. I could run an experiment.
